@startuml

class FIUBA {
+carreras: List<Carrera>
+alumnos: List<Alumno>

+ crearAlumno(datos de alumno...): Boolean
+ quitarAlumno(Integer: legajo): Boolean
+ crearCarrera(datos de carrera...): Boolean
+ quitarCarrera(Integer: codigo): Boolean
+ incribirACarrera(Integer: legajo, Integer: codigo): Boolean
+ consultarEstado(Integer: legajo, Integer: codigo): ???
+ marcarComoAprobada(Integer: legajo, Integer: codigo): Boolean
}

class Alumno {
+ agregarCarrera(Carrera: carrera): void
+ quitarCarrera(Carrera: carrera): Integer
+ consultarEstado(Integer: codigo): ???
+ aprobarMateria(Integer: codigoCarrera, Integer: codigoMateria)
}

class Carrera {
+ crearMateria(datos materia...): Boolean|void
+ quitarMateria(Integer: codigo): Boolean
+ obtenerCreditosTotales(): Integer
}

class Materia {

}

class Buscador {
+ pertenece(List T: items, Predicate T: criterio): Boolean
+ buscar(List T: items, Predicate T: criterio): T
}

FIUBA "1" *--- "many" Alumno
FIUBA "1" *--- "many" Carrera
FIUBA o--> Buscador
Carrera o--> Buscador
Alumno o--> Buscador
Carrera "1" o--- "many" Materia

@enduml